CREATE TABLE `docs` (
	`id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`file_name` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
    `location` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`size` INT(10) NULL DEFAULT NULL,
	`doc_create_date` DATETIME NULL DEFAULT NULL,
	`doc_modified_date` DATETIME NULL DEFAULT NULL,
	`md5` TINYTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`create_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`create_by` INT(10) NULL DEFAULT NULL,
	`update_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	`update_by` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `file_name` (`file_name`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;