name: build-and-upload-jar

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Build JAR
        run: mvn -B clean package -DskipTests

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar